server:
  port: 3000
  servlet:
    context-path: /api/v1

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 597088031575-nqsoc5a86925lfk4ctslarhnlhcvvjak.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile


  application:
    name: crm-backend-api

  datasource:
    url: jdbc:mysql://localhost:3307/crm_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: crmuser
    password: crmpassword
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  redis:
    host: localhost
    port: 6379
    lettuce:
      pool:
        max-active: 20
        max-idle: 10
        min-idle: 5
        max-wait: -1ms
      shutdown-timeout: 2000ms


logging:
  level:
    com.xeno.crm: DEBUG
    org.springframework.data.redis: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics


springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
    try-it-out-enabled: true
  show-actuator: false

  info:
    title: CRM Backend API
    description: API documentation for the Xeno CRM application.
    version: v1.0.0
app:
  jwt:
    secret: YOUR_SUPER_SECRET_KEY_THAT_IS_AT_LEAST_256_BITS_LONG
    expiration-ms: 86400000 # 24 hours
  oauth2:
    redirect-uri: http://localhost:4200/login/callback # Your frontend callback URL