import './global.css';
import { Header } from '../components/Header';

export const metadata = {
  title: 'Welcome to frontend',
  description: 'Generated by create-nx-workspace',
};

import { Suspense } from 'react';
import { RouteGuard } from '../components/RouteGuard';

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        <Suspense fallback={<div>Loading...</div>}>
          <RouteGuard>{children}</RouteGuard>
        </Suspense>
      </body>
    </html>
  );
}
